"""<b>Save Croped Objects </b> Crops objects from an image and saves the croped
images.
<hr>
In order to process large images it can be benefitial to crop regions of
interest out. This module will crop out segmented images from an object and
save the cropped images as well as the masks used.
<p>You can choose from many different image formats for saving your files. This
allows you to use the module as a file format converter, by loading files
in their original format and then saving them in an alternate format.</p>

<p>Note that saving images in 12-bit format is not supported, and 16-bit format
is supported for TIFF only.</p>

See also <b>NamesAndTypes</b>, <b>ConserveMemory</b>.
"""

import logging
import os

import numpy as np
import scipy.ndimage as ndi

logger = logging.getLogger(__name__)
import skimage.io
import skimage.util

import cellprofiler_core.module as cpm
import cellprofiler_core.setting as cps
from cellprofiler_core.setting.text import Text, Integer, Directory
from cellprofiler_core.setting.choice import Choice
from cellprofiler_core.setting.subscriber import ImageSubscriber, FileImageSubscriber
from cellprofiler_core.setting.text import Text, Integer, Directory

from cellprofiler_core.preferences import ABSOLUTE_FOLDER_NAME
from cellprofiler_core.preferences import DEFAULT_INPUT_FOLDER_NAME
from cellprofiler_core.preferences import DEFAULT_INPUT_SUBFOLDER_NAME
from cellprofiler_core.preferences import DEFAULT_OUTPUT_FOLDER_NAME
from cellprofiler_core.preferences import DEFAULT_OUTPUT_SUBFOLDER_NAME

YES, NO = "Yes", "No"
from cellprofiler_core.constants.measurement import (
    C_FILE_NAME,
    C_PATH_NAME,
    C_URL,
    COLTYPE_VARCHAR_FILE_NAME,
    COLTYPE_VARCHAR_PATH_NAME,
)


import cellprofiler_core.utilities.pathname

NOTDEFINEDYET = "Helptext Not Defined Yet"
USING_METADATA_TAGS_REF = NOTDEFINEDYET
USING_METADATA_HELP_REF = NOTDEFINEDYET
IO_FOLDER_CHOICE_HELP_TEXT = NOTDEFINEDYET
IO_WITH_METADATA_HELP_TEXT = NOTDEFINEDYET

IF_IMAGE = "Image"
IF_MASK = "Mask"
IF_CROPPING = "Cropping"
IF_FIGURE = "Module window"
IF_MOVIE = "Movie"
IF_OBJECTS = "Objects"
IF_ALL = [IF_IMAGE, IF_MASK, IF_CROPPING, IF_MOVIE, IF_OBJECTS]

OLD_BIT_DEPTH_8 = "8"
OLD_BIT_DEPTH_16 = "16"
BIT_DEPTH_8 = "8-bit integer"
BIT_DEPTH_16 = "16-bit integer"
BIT_DEPTH_FLOAT = "32-bit floating point"

FN_FROM_IMAGE = "From image filename"
FN_SEQUENTIAL = "Sequential numbers"
FN_SINGLE_NAME = "Single name"
SINGLE_NAME_TEXT = "Enter single file name"
FN_WITH_METADATA = "Name with metadata"
FN_IMAGE_FILENAME_WITH_METADATA = "Image filename with metadata"
METADATA_NAME_TEXT = """Enter file name with metadata"""
SEQUENTIAL_NUMBER_TEXT = "Enter file prefix"
FF_BMP = "bmp"
FF_JPG = "jpg"
FF_JPEG = "jpeg"
FF_PBM = "pbm"
FF_PCX = "pcx"
FF_PGM = "pgm"
FF_PNG = "png"
FF_PNM = "pnm"
FF_PPM = "ppm"
FF_RAS = "ras"
FF_TIF = "tif"
FF_TIFF = "tiff"
FF_H5 = "h5"
AXIS_Z = "Z (Slice)"
AXIS_T = "T (Time)"

# This is the Axistag for zyxc images for Ilastik compatible h5 image
# as described here: https://github.com/ilastik/ilastik/blob/master/bin/combine_channels_as_h5.py
# generated by: vigra.defaultAxistags('zyxc').toJSON()
H5_ZYXC_AXISTAG = """{\n  "axes": [\n    {\n      "key": "z",\n
      "typeFlags": 2,\n
 "resolution": 0,\n      "description": ""\n    },\n
 {\n      "key": "y",\n      "typeFlags": 2,\n      "resolution": 0,\n
   "description": ""\n    },\n    {\n      "key": "x",\n
    "typeFlags": 2,\n      "resolution": 0,\n
 "description": ""\n    },\n    {\n      "key": "c",\n
    "typeFlags": 1,\n      "resolution": 0,\n
 "description": ""\n    }\n  ]\n}"""

PC_WITH_IMAGE = "Same folder as image"
OLD_PC_WITH_IMAGE_VALUES = ["Same folder as image"]
PC_CUSTOM = "Custom"
PC_WITH_METADATA = "Custom with metadata"
WS_EVERY_CYCLE = "Every cycle"
WS_FIRST_CYCLE = "First cycle"
WS_LAST_CYCLE = "Last cycle"
CM_GRAY = "gray"

GC_GRAYSCALE = "Grayscale"
GC_COLOR = "Color"

"""Offset to the directory path setting"""
OFFSET_DIRECTORY_PATH = 11

"""Offset to the bit depth setting in version 11"""
OFFSET_BIT_DEPTH_V11 = 12


class SaveObjectCrops(cpm.Module):

    module_name = "SaveObjectCrops"
    variable_revision_number = 3
    category = ["ImcPluginsCP", "File Processing"]

    def create_settings(self):
        self.input_type = Choice("Select the type of input", [IF_IMAGE], IF_IMAGE)

        self.image_name = cps.subscriber.ImageSubscriber(
            "Select the image to save",
            "None",
            doc="""
            <i>(Used only if "%(IF_IMAGE)s", "%(IF_MASK)s" or "%(IF_CROPPING)s" are selected to save)</i><br>
            Select the image you want to save."""
            % globals(),
        )

        self.input_object_name = cps.subscriber.LabelSubscriber(
            "Select the objects to save", "None"
        )

        self.objects_name = cps.subscriber.LabelSubscriber(
            "Select the objects to crop and save",
            "None",
            doc="""
            Select the objects that you want to save."""
            % globals(),
        )

        self.file_name_method = Choice(
            "Select method for constructing file names",
            [
                FN_FROM_IMAGE,
            ],
            doc="""
            Several choices are available for constructing the image file name:
            <ul>
            <li><i>%(FN_FROM_IMAGE)s:</i> The filename will be constructed based
            on the original filename of an input image specified in <b>NamesAndTypes</b>.
            You will have the opportunity to prefix or append
            additional text.
            <p>If you have metadata associated with your images, you can append an text
            to the image filename using a metadata tag. This is especially useful if you
            want your output given a unique label according to the metadata corresponding
            to an image group. The name of the metadata to substitute can be provided for
            each image for each cycle using the <b>Metadata</b> module.
            %(USING_METADATA_TAGS_REF)s%(USING_METADATA_HELP_REF)s.</p></li>
            </ul>"""
            % globals(),
        )

        self.file_image_name = FileImageSubscriber(
            "Select image name for file prefix",
            "None",
            doc="""
            <i>(Used only when "%(FN_FROM_IMAGE)s" is selected for contructing the filename)</i><br>
            Select an image loaded using <b>NamesAndTypes</b>. The original filename will be
            used as the prefix for the output filename."""
            % globals(),
        )

        self.wants_file_name_suffix = cps.Binary(
            "Append a suffix to the image file name?",
            False,
            doc="""
            Select <i>%(YES)s</i> to add a suffix to the image's file name.
            Select <i>%(NO)s</i> to use the image name as-is."""
            % globals(),
        )

        self.file_name_suffix = cps.text.Text(
            "Text to append to the image name",
            "",
            metadata=True,
            doc="""
            <i>(Used only when constructing the filename from the image filename)</i><br>
            Enter the text that should be appended to the filename specified above.""",
        )

        self.file_format = cps.choice.Choice(
            "Saved file format",
            [FF_TIFF],
            value=FF_TIFF,
            doc="""
            <i>(Used only when saving non-movie files)</i><br>
            Select the image or movie format to save the image(s). Most common
            image formats are available; MAT-files are readable by MATLAB.""",
        )

        self.pathname = SaveImagesDirectoryPath(
            "Output file location",
            self.file_image_name,
            doc="""
            <i>(Used only when saving non-movie files)</i><br>
            This setting lets you choose the folder for the output
            files. %(IO_FOLDER_CHOICE_HELP_TEXT)s
            <p>An additional option is the following:
            <ul>
            <li><i>Same folder as image</i>: Place the output file in the same folder
            that the source image is located.</li>
            </ul></p>
            <p>%(IO_WITH_METADATA_HELP_TEXT)s %(USING_METADATA_TAGS_REF)s.
            For instance, if you have a metadata tag named
            "Plate", you can create a per-plate folder by selecting one the subfolder options
            and then specifying the subfolder name as "\g&lt;Plate&gt;". The module will
            substitute the metadata values for the current image set for any metadata tags in the
            folder name.%(USING_METADATA_HELP_REF)s.</p>
            <p>If the subfolder does not exist when the pipeline is run, CellProfiler will
            create it.</p>
            <p>If you are creating nested subfolders using the sub-folder options, you can
            specify the additional folders separated with slashes. For example, "Outlines/Plate1" will create
            a "Plate1" folder in the "Outlines" folder, which in turn is under the Default
            Input/Output Folder. The use of a forward slash ("/") as a folder separator will
            avoid ambiguity between the various operating systems.</p>"""
            % globals(),
        )

        self.bit_depth = cps.choice.Choice(
            "Image bit depth",
            [BIT_DEPTH_8, BIT_DEPTH_16, BIT_DEPTH_FLOAT],
            doc="""
            <i>(Used only when saving files in a non-MAT format)</i><br>
            Select the bit-depth at which you want to save the images.
            <i>%(BIT_DEPTH_FLOAT)s</i> saves the image as floating-point decimals
            with 32-bit precision in its raw form, typically scaled between
            0 and 1.
            <b>%(BIT_DEPTH_16)s and %(BIT_DEPTH_FLOAT)s images are supported only
            for TIF formats. Currently, saving images in 12-bit is not supported.</b>"""
            % globals(),
        )

        self.object_extension = Integer(
            "Object extension",
            value=1,
            doc="""
            How many pixels should the bounding box of the objects be extended
                                            before cropping""",
        )

        self.overwrite = cps.Binary(
            "Overwrite existing files without warning?",
            False,
            doc="""
            Select <i>%(YES)s</i> to automatically overwrite a file if it already exists.
            Select <i>%(NO)s</i> to be prompted for confirmation first.
            <p>If you are running the pipeline on a computing cluster,
            select <i>%(YES)s</i> since you will not be able to intervene and answer the confirmation prompt.</p>"""
            % globals(),
        )

        self.when_to_save = cps.choice.Choice(
            "When to save",
            [WS_FIRST_CYCLE],
            doc="""<a name='when_to_save'>
            <i>(Used only when saving non-movie files)</i><br>
            Specify at what point during pipeline execution to save file(s). </a>
            <ul>
            <li><i>%(WS_EVERY_CYCLE)s:</i> Useful for when the image of interest is created every cycle and is
            not dependent on results from a prior cycle.</li>
            </ul> """
            % globals(),
        )

        self.update_file_names = cps.Binary(
            "Record the file and path information to the saved image?",
            False,
            doc="""
            Select <i>%(YES)s</i> to store filename and pathname data for each of the new files created
            via this module as a per-image measurement.
            <p>Instances in which this information may be useful include:
            <ul>
            <li>Exporting measurements to a database, allowing
            access to the saved image. If you are using the machine-learning tools or image
            viewer in CellProfiler Analyst, for example, you will want to enable this setting if you want
            the saved images to be displayed along with the original images.</li>
            <li>Allowing downstream modules (e.g., <b>CreateWebPage</b>) to access
            the newly saved files.</li>
            </ul></p>"""
            % globals(),
        )

        self.create_subdirectories = cps.Binary(
            "Create subfolders in the output folder?",
            False,
            doc="""
            Select <i>%(YES)s</i> to create subfolders to match the input image folder structure."""
            % globals(),
        )

        self.root_dir = cps.text.Directory(
            "Base image folder",
            doc="""
            <i>Used only if creating subfolders in the output folder</i>
            In subfolder mode, <b>SaveImages</b> determines the folder for
            an image file by examining the path of the matching input file.
            The path that SaveImages uses is relative to the image folder
            chosen using this setting. As an example, input images might be stored
            in a folder structure of "images%(sep)s<i>experiment-name</i>%(sep)s
            <i>date</i>%(sep)s<i>plate-name</i>". If the image folder is
            "images", <b>SaveImages</b> will store images in the subfolder,
            "<i>experiment-name</i>%(sep)s<i>date</i>%(sep)s<i>plate-name</i>".
            If the image folder is "images%(sep)s<i>experiment-name</i>",
            <b>SaveImages</b> will store images in the subfolder,
            <i>date</i>%(sep)s<i>plate-name</i>".
            """
            % dict(sep=os.path.sep),
        )

    def settings(self):
        """Return the settings in the order to use when saving"""
        return [
            self.input_type,
            self.input_object_name,
            self.image_name,
            self.objects_name,
            self.object_extension,
            self.file_name_method,
            self.file_image_name,
            self.wants_file_name_suffix,
            self.file_name_suffix,
            self.file_format,
            self.pathname,
            self.bit_depth,
            self.overwrite,
            self.when_to_save,
            self.update_file_names,
            self.create_subdirectories,
            self.root_dir,
        ]

    def visible_settings(self):
        """Return only the settings that should be shown"""
        result = []
        result.append(self.input_type)
        if self.input_type.value == IF_IMAGE:
            result.append(self.image_name)
        else:
            result.append(self.input_object_name)
        result.append(self.objects_name)
        result.append(self.object_extension),
        result.append(self.file_name_method)
        if self.file_name_method == FN_FROM_IMAGE:
            result += [self.file_image_name, self.wants_file_name_suffix]
            if self.wants_file_name_suffix:
                result.append(self.file_name_suffix)
        else:
            raise NotImplementedError(
                "Unhandled file name method: %s" % (self.file_name_method)
            )
        result.append(self.file_format)
        result.append(self.bit_depth)
        result.append(self.pathname)
        result.append(self.overwrite)
        result.append(self.update_file_names)
        if self.file_name_method == FN_FROM_IMAGE:
            result.append(self.create_subdirectories)
            if self.create_subdirectories:
                result.append(self.root_dir)
        return result

    @property
    def module_key(self):
        return "%s_%d" % (self.module_name, self.module_num)

    def prepare_group(self, workspace, grouping, image_numbers):
        return True

    def prepare_to_create_batch(self, workspace, fn_alter_path):
        self.pathname.alter_for_create_batch_files(fn_alter_path)
        if self.create_subdirectories:
            self.root_dir.alter_for_create_batch_files(fn_alter_path)

    def run(self, workspace):
        """Run the module

        pipeline     - instance of cellprofiler_core.pipeline for this run
        workspace    - the workspace contains:
            image_set    - the images in the image set being processed
            object_set   - the objects (labeled masks) in this image set
            measurements - the measurements for this run
            frame        - display within this frame (or None to not display)
        """
        should_save = self.run_crops(workspace)
        workspace.display_data.filename = self.get_filename(
            workspace, make_dirs=False, check_overwrite=False
        )

    def display(self, workspace, figure):
        if self.show_window:
            figure.set_subplots((1, 1))
            outcome = (
                "Wrote %s" if workspace.display_data.wrote_image else "Did not write %s"
            )
            figure.subplot_table(0, 0, [[outcome % (workspace.display_data.filename)]])

    def run_crops(self, workspace):
        """Handle cropping of an image by objects"""
        #
        # First, check to see if we should save this image
        #
        self.save_crops(workspace)
        return True

    def _extend_slice(self, sl, extent, dim_max, dim_min=0):
        """
        helper function to extend single slices
        :param sl: numpy slice
        :param extent: how many pixels should be extended
        :param dim_max: maximum coordinate in dimension
        :param dim_min: minimum coordinate in dimension, e.g. 0
        :return: the new extended slice
        """

        x_start = max(sl.start - extent, dim_min)
        x_end = min(sl.stop + extent, dim_max)
        return np.s_[x_start:x_end]

    def _extend_slice_touple(self, slice_touple, extent, max_dim, min_dim=(0, 0)):
        """
        Helper for save_crops
        Extends a numpy slice touple, e.g. corresponding to a bounding box
        :param slice_touple: a numpy slice
        :param extent: amount of extension in pixels
        :param max_dim: maximum image coordinates (e.g. from img.shape)
        :param min_dim: minimum image coordinates, usually (0,0)
        :return: an extended numpy slice

        """
        new_slice = tuple(
            self._extend_slice(s, extent, d_max, d_min)
            for s, d_max, d_min in zip(slice_touple, max_dim, min_dim)
        )

        return new_slice

    def _save_object_stack(self, folder, basename, img_stack, slices, labels=None):
        """
        Saves slices from an image stack as.
        :param folder: The folder to save it in
        :param basename: The filename
        :param img_stack: the image stack. should be CXY
        :param slices: a list of numpy slices sphecifying the regions to be saved
        :return:
        """
        if labels is None:
            labels = range(slices)
        for lab, sl in zip(labels, slices):
            if sl is None:
                pass
            x = sl[0].start
            y = sl[1].start

            exsl = tuple([np.s_[:]] + [s for s in sl])

            fn = os.path.join(
                folder,
                basename
                + "_l"
                + str(lab + 1)
                + "_x"
                + str(x)
                + "_y"
                + str(y)
                + ".tiff",
            )
            timg = img_stack[exsl]
            skimage.io.imsave(fn, timg, plugin="tifffile", imagej=True)

    def save_crops(self, workspace):
        """ Crops the image by objects """
        objects_name = self.objects_name.value
        objects = workspace.object_set.get_objects(objects_name)
        bit_depth = self.bit_depth.value
        if self.input_type == IF_IMAGE:
            image_name = self.image_name.value
            image = workspace.image_set.get_image(image_name)
            pixels = image.pixel_data
        elif self.input_type == IF_OBJECTS:
            obj_name = self.input_object_name.value
            inp_obj = workspace.object_set.get_objects(obj_name)
            pixels = inp_obj.get_segmented()
        else:
            raise ("invalid choice of input")

        filename = self.get_filename(workspace)
        object_extension = self.object_extension.value
        if filename is None:  # failed overwrite check
            return

        slices = ndi.find_objects(objects.segmented)
        slices, labels = zip(
            *[(s, label) for label, s in enumerate(slices) if s is not None]
        )

        ext_slices = [
            self._extend_slice_touple(
                sl, object_extension, [pixels.shape[0], pixels.shape[1]]
            )
            for sl in slices
        ]
        out_folder = os.path.dirname(filename)
        basename = os.path.splitext(os.path.basename(filename))[0]
        #  the stack for imctools needs to be cxy, while it is xyc in cp
        if len(pixels.shape) == 2:
            stack = pixels.reshape([1] + list(pixels.shape))
        else:
            stack = np.rollaxis(pixels, 2, 0)

        # fix the dtype
        if bit_depth == BIT_DEPTH_8:
            stack = skimage.util.img_as_ubyte(stack)
        elif bit_depth == BIT_DEPTH_16:
            stack = skimage.util.img_as_uint(stack)
        elif bit_depth == BIT_DEPTH_FLOAT:
            stack = skimage.util.img_as_float(stack).astype(np.float32)

        self._save_object_stack(out_folder, basename, stack, ext_slices, labels)
        self.save_filename_measurements(workspace)
        if self.show_window:
            workspace.display_data.wrote_image = True

    def post_group(self, workspace, *args):
        pass

    def check_overwrite(self, filename, workspace):
        """Check to see if it's legal to overwrite a file

        Throws an exception if can't overwrite and no interaction available.
        Returns False if can't overwrite, otherwise True.
        """
        if not self.overwrite.value and os.path.isfile(filename):
            try:
                return (
                    workspace.interaction_request(
                        self, workspace.measurements.image_set_number, filename
                    )
                    == "Yes"
                )
            except workspace.NoInteractionException:
                raise ValueError(
                    'SaveImages: trying to overwrite %s in headless mode, but Overwrite files is set to "No"'
                    % (filename)
                )
        return True

    def handle_interaction(self, image_set_number, filename):
        """handle an interaction request from check_overwrite()"""
        import wx

        dlg = wx.MessageDialog(
            wx.GetApp().TopWindow,
            "%s #%d, set #%d - Do you want to overwrite %s?"
            % (self.module_name, self.module_num, image_set_number, filename),
            "Warning: overwriting file",
            wx.YES_NO | wx.ICON_QUESTION,
        )
        result = dlg.ShowModal() == wx.ID_YES
        return "Yes" if result else "No"

    def save_filename_measurements(self, workspace):
        if self.update_file_names.value:
            filename = self.get_filename(
                workspace, make_dirs=False, check_overwrite=False
            )
            pn, fn = os.path.split(filename)
            url = cellprofiler_core.utilities.pathname.pathname2url(filename)
            workspace.measurements.add_measurement(
                "Image",
                self.file_name_feature,
                fn,
            )
            workspace.measurements.add_measurement(
                "Image",
                self.path_name_feature,
                pn,
            )
            workspace.measurements.add_measurement(
                "Image",
                self.url_feature,
                url,
            )

    @property
    def file_name_feature(self):
        return "_".join((C_FILE_NAME, self.image_name.value))

    @property
    def path_name_feature(self):
        return "_".join((C_PATH_NAME, self.image_name.value))

    @property
    def url_feature(self):
        return "_".join((C_URL, self.image_name.value))

    @property
    def source_file_name_feature(self):
        """The file name measurement for the exemplar disk image"""
        return "_".join((C_FILE_NAME, self.file_image_name.value))

    def source_path(self, workspace):
        """The path for the image data, or its first parent with a path"""
        if self.file_name_method.value == FN_FROM_IMAGE:
            path_feature = "%s_%s" % (
                C_PATH_NAME,
                self.file_image_name.value,
            )
            assert workspace.measurements.has_feature("Image", path_feature), (
                "Image %s does not have a path!" % self.file_image_name.value
            )
            return workspace.measurements.get_current_image_measurement(path_feature)

        # ... otherwise, chase the cpimage hierarchy looking for an image with a path
        cur_image = workspace.image_set.get_image(self.image_name.value)
        while cur_image.path_name is None:
            cur_image = cur_image.parent_image
            assert (
                cur_image is not None
            ), "Could not determine source path for image %s' % (self.image_name.value)"
        return cur_image.path_name

    def get_measurement_columns(self, pipeline):
        if self.update_file_names.value:
            return [
                (
                    "Image",
                    self.file_name_feature,
                    COLTYPE_VARCHAR_FILE_NAME,
                ),
                (
                    "Image",
                    self.path_name_feature,
                    COLTYPE_VARCHAR_PATH_NAME,
                ),
            ]
        else:
            return []

    def get_filename(self, workspace, make_dirs=True, check_overwrite=True):
        """Concoct a filename for the current image based on the user settings"""

        measurements = workspace.measurements
        file_name_feature = self.source_file_name_feature
        filename = measurements.get_current_measurement("Image", file_name_feature)
        filename = os.path.splitext(filename)[0]
        if self.wants_file_name_suffix:
            suffix = self.file_name_suffix.value
            suffix = workspace.measurements.apply_metadata(suffix)
            filename += suffix

        filename = "%s.%s" % (filename, self.get_file_format())
        pathname = self.pathname.get_absolute_path(measurements)
        if self.create_subdirectories:
            image_path = self.source_path(workspace)
            subdir = os.path.relpath(image_path, self.root_dir.get_absolute_path())
            pathname = os.path.join(pathname, subdir)
        if len(pathname) and not os.path.isdir(pathname) and make_dirs:
            try:
                os.makedirs(pathname)
            except:
                #
                # On cluster, this can fail if the path was created by
                # another process after this process found it did not exist.
                #
                if not os.path.isdir(pathname):
                    raise
        result = os.path.join(pathname, filename)
        if check_overwrite and not self.check_overwrite(result, workspace):
            return

        if check_overwrite and os.path.isfile(result):
            try:
                os.remove(result)
            except:
                import bioformats

                bioformats.clear_image_reader_cache()
                os.remove(result)
        return result

    def get_file_format(self):
        """Return the file format associated with the extension in self.file_format"""
        # if self.save_image_or_figure == IF_MOVIE:
        #    return self.movie_format.value
        return self.file_format.value

    def get_bit_depth(self):
        if (
            self.save_image_or_figure == IF_IMAGE
            and self.get_file_format() in FF_SUPPORTING_16_BIT
        ):
            return self.bit_depth.value
        else:
            return BIT_DEPTH_8

    def upgrade_settings(self, setting_values, variable_revision_number, module_name):
        """Adjust the setting values to be backwards-compatible with old versions"""
        if variable_revision_number < 2:
            setting_values = [IF_IMAGE, "None"] + setting_values
        if variable_revision_number < 3:
            setting_values[11] = BIT_DEPTH_FLOAT
        return setting_values, variable_revision_number

    def validate_module(self, pipeline):
        # if (self.save_image_or_figure in (IF_IMAGE, IF_MASK, IF_CROPPING) and
        #    self.when_to_save in (WS_FIRST_CYCLE, WS_EVERY_CYCLE)):
        #
        # Make sure that the image name is available on every cycle
        #
        #    for setting in cps.get_name_providers(pipeline,
        #                                          self.image_name):
        #        if setting.provided_attributes.get(cps.AVAILABLE_ON_LAST_ATTRIBUTE):
        #
        # If we fell through, then you can only save on the last cycle
        #
        #            raise cps.ValidationError("%s is only available after processing all images in an image group" %
        #                                      self.image_name.value,
        #                                      self.when_to_save)

        # XXX - should check that if file_name_method is
        # FN_FROM_IMAGE, that the named image actually has the
        # required path measurement

        # Make sure metadata tags exist
        pass


class SaveImagesDirectoryPath(Directory):
    """A specialized version of Directory to handle saving in the image dir"""

    def __init__(self, text, file_image_name, doc):
        """Constructor
        text - explanatory text to display
        file_image_name - the file_image_name setting so we can save in same dir
        doc - documentation for user
        """
        super(SaveImagesDirectoryPath, self).__init__(
            text,
            dir_choices=[
                DEFAULT_OUTPUT_FOLDER_NAME,
                DEFAULT_INPUT_FOLDER_NAME,
                PC_WITH_IMAGE,
                ABSOLUTE_FOLDER_NAME,
                DEFAULT_OUTPUT_SUBFOLDER_NAME,
                DEFAULT_INPUT_SUBFOLDER_NAME,
            ],
            doc=doc,
        )
        self.file_image_name = file_image_name

    def get_absolute_path(self, measurements=None, image_set_index=None):
        if self.dir_choice == PC_WITH_IMAGE:
            path_name_feature = "PathName_%s" % self.file_image_name.value
            return measurements.get_current_image_measurement(path_name_feature)
        return super(SaveImagesDirectoryPath, self).get_absolute_path(
            measurements, image_set_index
        )

    def test_valid(self, pipeline):
        if self.dir_choice not in self.dir_choices:
            raise ValidationError(
                "%s is not a valid directory option" % self.dir_choice, self
            )


def save_h5(path, pixels, volumetric):
    """Saves an image to an hdf5 with zyxc axistag
    This format should be good for ilastik pixel classification for multiplexed images
    This is adapted from: https://github.com/ilastik/ilastik/blob/master/bin/combine_channels_as_h5.py
    path - path to file image
    pixels - the pixel data
    pixel_dtype - the output pixel dtype
    """

    # Adapt the pixels shape to zyxc
    origin_shape = list(pixels.shape)
    if len(origin_shape) == 2:  # a yx stack
        target_shape = origin_shape + [1]
        # reshape to yxc
        pixels = pixels.reshape(target_shape)

    origin_shape = list(pixels.shape)
    if len(origin_shape) == 3:
        if volumetric:  # zyx stack
            target_shape = origin_shape + [1]
        else:  # yxc stack
            target_shape = [1] + origin_shape
        pixels = pixels.reshape(target_shape)
    with h5py.File(path, "w") as f:
        imgname = os.path.basename(os.path.splitext(path)[0])
        dset = f.create_dataset(
            imgname, shape=pixels.shape, dtype=pixels.dtype, chunks=True
        )
        dset.attrs["axistags"] = H5_ZYXC_AXISTAG
        dset[:, :, :, :] = pixels
